name: Some workflow
on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
        description: The name of the app
  workflow_dispatch:
    inputs:
      APP:
        description: The name of the app
env:
  APP: ${{ inputs.APP }}

jobs:
  cron-test:
    runs-on: ubuntu-latest
    steps:
        - name: Print the name of the app
          shell: bash
          run: echo "$APP"