name: Cron job invoking a workflow
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/15 * * * *'
jobs:
  cron-test:
    uses: shekelboi/GHA-testing/.github/workflows/app.yaml@main
    with:
      APP: "test"