name: Testing action
on:
  workflow_dispatch:

jobs:
  cron-test:
    runs-on: ubuntu-latest
    steps:
        - name: test
          uses: shekelboi/TestAction@main
          with:
            slack_hook: I'm set